### ISSUE TITLE
Bug corrected but not on stable

### ISSUE THREAD

**Issue by thiagomsantanna** [Jon-Becker/node-temp-mail#2]
Bug with multiple e-mails was corrected (https://github.com/Jon-Becker/node-temp-mail/commit/5a5cbc215c2217a55ffeda52326439d4fa6002cc) but is not on latest stable version. So, when going to install the package and use it the bug still occurs

![image](https://user-images.githubusercontent.com/67112597/202791759-795a15b5-644c-4472-8bc1-4a8b3a26d899.png)

**Comment by Jon-Becker** [comment]
I'll update the tag. I believe 1.0.2 posted on NPM already includes these changes
