### ISSUE TITLE
Downloading the package using npm gives an outdated file

### ISSUE THREAD

**Issue by ToberoCat** [Jon-Becker/node-temp-mail#3]
I've downloaded the package using npm. I've typed `npm i node-temp-mail`. It installed. But as soon as I received two mails, it crashed. After further investigation, I found that the issue were wrong arguments that got passed into the method call when the final size is bigger than 2.

When I fixed the bug locally and tried to upload I saw that these changes were already made. Therefore I wanted to tell you that it looks like I installed an older file or something with this bug still being in it. I don't know if you can do anything about it.

**Comment by Jon-Becker** [comment]
Hey! I'll look into this for you today.

**Comment by a-rustacean** [comment]
Hello @ToberoCat, We appreciate you raising this issue. As you've mentioned, the fix has already been implemented in PR #1. However, the issue persists because a new version hasn't been released on NPM yet. We'll make it a priority to publish a new version on NPM as soon as possible.

**Comment by Jon-Becker** [comment]
publishing package now

**Comment by Jon-Becker** [comment]
https://www.npmjs.com/package/node-temp-mail
